# Site settings
title:       GEVI
email:       gpernelle@gmail.com
author:      Guillaume Pernelle
description: "Blog to share data."
baseurl:     ""
url:         "http://gpernelle.github.io"
date_format: "%b %-d, %Y"
port: 4001
# Google services
google_verification: googleec1b083785e99a22
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-10813752-3
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: gpernelle
bitbucket_username: gpernelle
stackoverflow_id:
twitter_username:
skype_username: #guillaume.pernelle
steam_nickname:
google_plus_id:
linkedin_username: guillaumepernelle
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'gpernelle@gmail.com'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
#markdown:     redcarpet
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
kramdown:
  input: GFM
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
